---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    rebase-strategy: disabled
    schedule:
      interval: "cron"
      cronjob: "30 1 * * *"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
      - "/actions/*"
    rebase-strategy: disabled
    schedule:
      interval: "cron"
      cronjob: "0 2 * * *"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    groups:
      docker-actions:
        applies-to: version-updates
        patterns:
          - "docker/*"
      github-actions:
        applies-to: version-updates
        patterns:
          - "actions/*"
          - "github/*"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    rebase-strategy: disabled
    schedule:
      interval: "cron"
      cronjob: "30 2 * * *"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
